### ISSUE TITLE
REGIS OSerror

### ISSUE THREAD

**Issue by martinvonk** [ArtesiaWater/hydropandas#113]
`.get_regis_layers()` raises an OSError:

> OSError: [Errno -68] NetCDF: I/O failure: '[http://www.dinodata.nl:80/opendap/REGIS/REGIS.nc](http://www.dinodata.nl/opendap/REGIS/REGIS.nc)'
>     # src/netCDF4/_netCDF4.pyx:2012: OSError
>     # ----------------------------- Captured stderr call -----------------------------
>     # Error:curl error: Problem with the SSL CA cert (path? access rights?)
>     # curl error details:
>     # Warning:oc_open: Could not read url

Temporarily fixed (ugly) with :
https://github.com/ArtesiaWater/hydropandas/pull/112/commits/f4f89ce00164eb2c6153804479d03ed96557c5fb

Maybe @rubencalje is familiar with this issue? Maybe it has something to do with the netCDF4 python package?

**Comment by OnnoEbbens** [comment]
Locally it does work for me. I tried with the newest netCDF4 version 1.6.3 and xarray version 2023.2.0 and it still works so I don't know what the issue is.

**Comment by martinvonk** [comment]
Maybe a linux issue? @dbrakenhoff
