### ISSUE TITLE
.plots.section_plot: better xlim's

### ISSUE THREAD

**Issue by HMEUW** [ArtesiaWater/hydropandas#115]
The observation plot of section_plot needs better xlims:

- without tmin specifed: why does the xaxis start 1992, that is 4.5 years before first observation.
- when tmin is specified: the lower bound of de xaxis does not match with the tmin value. I don't like that, because it suggests there are no observations in 2015.

Does someone knows why the xlims are chosen by matplotlib this way? And an easy way to fix this, to achieve an elegant lower bound of the x-axis? In this example an x-limit at 1 jan 1997 is preferred, xticks are then at 1 jan every 3 or 4 years. For timeseries shorter than a few years, an exact start at tmin is better.

**tmin not specified**
![image](https://user-images.githubusercontent.com/117160147/227119617-c88ae8c6-9264-414e-8426-0012233412d9.png)

**tmin specified**
![image](https://user-images.githubusercontent.com/117160147/227119734-ed6cc054-0c48-4979-b2c6-8caea71bc1ec.png)

**start obs**
![image](https://user-images.githubusercontent.com/117160147/227120252-a0d352aa-b9f2-43f2-a612-aa4a20a49fc8.png)

**Comment by OnnoEbbens** [comment]
In the `section_plot` function a line is plotted using `p = ax_obs.plot(plot_df)`. Using this, matplotlib will pick an xlim in such a way that there is some white space before the start (and after the end) of the line. I think they do this so you can see exactly where the line starts (and ends).

When you specify `tmin` in the `section_plot` function the `plof_df` is sliced using `plot_df = self._obj.loc[name, "obs"][tmin:tmax][cols].copy()`. The plot is still created using `p = ax_obs.plot(plot_df)` so matplotlib will pick an xlim with some white space before the start of the sliced DataFrame.

I think the solution here is to set the xlim after the plot is created based on tmin and tmax for example: `ax_obs.set_xlim(tmin, tmax)`.

**Comment by HMEUW** [comment]
Thanks for your suggestion. I will implement for the option when tmin is set. I will do some research about the chosen xlim for the plot without tmin. A 4,5 year gap is a little bit too much for me.

Today I checked wether there is some NaN data in the dataset, that might cause the 4,5 year gap. There is no NaN data.

**Comment by martinvonk** [comment]
closed by #116
