### ISSUE TITLE
read_dino from zipfile eats disk space

### ISSUE THREAD

**Issue by FransSchaars** [ArtesiaWater/hydropandas#117]
Read_dino uses a unique tempfile to unzip. 
But it does not clean up after reading, eventually resulting in a full disk.
The solution would be to clean up and remove the temporary dir in dino.py->read_dino_dir.  

![image](https://user-images.githubusercontent.com/8067157/227540579-ec6eb0d9-decc-4c22-b525-cc0acf345032.png)

**Comment by OnnoEbbens** [comment]
Martin is going to fix this

**Comment by martinvonk** [comment]
![alt-text](https://media.giphy.com/media/sQQTpNAbQGztGoMPug/giphy.gif)

**Comment by martinvonk** [comment]
Fixed with #121

**Comment by FransSchaars** [comment]
Thank you! 
my disk will be very happy! 😉
