### ISSUE TITLE
Add option to allow for different ObsClasses in FEWS xml reader

### ISSUE THREAD

**Issue by martinvonk** [ArtesiaWater/hydropandas#119]
Sometimes there can be different Observation Classes in the same FEWS xml. These can be recognized using the parameterId. For instance, the parameterId's _h.G.w_ and _P.radar_ should return the type GroundwaterObs and PrecipitationObs respectively. 
Currently, the function https://github.com/ArtesiaWater/hydropandas/blob/0039a76eb4cf526b00350a8cfc970f382e8c8abc/hydropandas/obs_collection.py#L1216-L1232 
only takes one argument for `ObsClass`. It would be nice if we could maybe input a translation dictionary:
```Python
{"h.G.w" : hpd.GroundwaterObs, "P.radar": hpd.PreciptationObs}
```
This translation dictionary is of course different per waterboard.

**Comment by OnnoEbbens** [comment]
Good idea! Would you like to implement this?
