### ISSUE TITLE
Gohlke binaries no longer needed

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/hydropandas#129]
Lately I have not encountered problems installing the gdal, fiona, shapely packages using pip. 

Also I saw that the website of Gohlke with the binary wheels is no longer updated and archived.

A big part of our installing guide is about using the binaries and might be confusing. Shall we delete this part in the documentation?

**Comment by martinvonk** [comment]
Are the issues really resolved? If not, we can maybe refer to the pypi.org url of the packages so users can download the .whl files there if needed.

**Comment by martinvonk** [comment]
I still have issues with installing those libraries using pip
