### ISSUE TITLE
Add option to add all metadata to the ObsCollection using the `add_meta_to_df` method

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/hydropandas#134]
If you want to add metadata from the meta attribute of an Observation to the ObsCollection you have to specify the key you want to add. It would be nice to have the option to add all keys from the meta attribute of an Observation to the ObsCollection

**Comment by HMEUW** [comment]
I just included this option in the processing of Bronhouderportaal-BRO update  #135

Maybe include as a general function in stead?
