### ISSUE TITLE
Read logger files from Solinst Levelogger as Obs

### ISSUE THREAD

**Issue by HMEUW** [ArtesiaWater/hydropandas#182]
For slugtests I use Solinst Levelogger 5, because it has higher accuracy than the Diver-family and it can take 8 observations per second. Diver family is limited to 2 observation per second.

I would like to make a read function for the XML file from the Solinst-software.

**Comment by HMEUW** [comment]
Thanks to @MattBrst for his first idea that the XLE-file is actually an XML-file that can be processed by `pd.read_xml`.

First part of programming is committed.

**Comment by HMEUW** [comment]
Hi, this issue has been resolved in branch [182-read-logger-files-from-soilinst-levelogger-as-ob](https://github.com/ArtesiaWater/hydropandas/tree/182-read-logger-files-from-soilinst-levelogger-as-obs). I thought it was merged in the dev-branch. However, I cannot find it there. Branch 182 is lost. What happened?

**Comment by OnnoEbbens** [comment]
Branch 182 was merged into the dev branch and deleted. Usually when a pull request is merged we delete the branch to avoid having too many stale branches.

You can still see all the changes in the pull request: https://github.com/ArtesiaWater/hydropandas/pull/184. At the end of the pull request you find messages explaining this (and the option to restore the branch):

@[dbrakenhoff](https://github.com/dbrakenhoff) dbrakenhoff merged commit [b636a99](https://github.com/ArtesiaWater/hydropandas/commit/b636a9907835bec40ca0a04001fedb0d59042c3d) into dev [Jan 15, 2024](https://github.com/ArtesiaWater/hydropandas/pull/184#event-11485329515)
7 checks passed

@[dbrakenhoff](https://github.com/dbrakenhoff) dbrakenhoff deleted the 182-read-logger-files-from-soilinst-levelogger-as-obs branch

So I will close this issue now. I try to make a new release next week.
