### ISSUE TITLE
update requirements?

### ISSUE THREAD

**Issue by HMEUW** [ArtesiaWater/hydropandas#196]
I used hydropandas 0.11 in a new environment. I only installed the packages listed in the hydropandas requirements.

Then, the Solinst import module was not working. It requires:

- lxml
- etree
- pyproj

Should we include these packages in the hydropandas requirements file? Or skip it, because the solinst package is a very specific one?

**Comment by OnnoEbbens** [comment]
Hi Hendrik, for certain submodules, such as Solinst, hydropandas has optional dependencies that are not installed by default (to avoid installing a lot of unwanted modules). If you want to install all the optional dependencies as well you can install hydropandas using `pip install hydropandas[full]`

I don't see 'etree' listed as an optional dependency. I assumed it was a built-in python module but I will check this.

**Comment by HMEUW** [comment]
Thanks for the swift reply and `full` explanation. I did not know that option was available.
