### ISSUE TITLE
fill missing obs behavior changed with KNMI update

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/hydropandas#205]
The behavior of the fill_missing_obs option in read_knmi has changed since the last PR. For some reason it cannot fill one date and will try every station to fill the data. The difference is most clear in the KNMI example notebook. 

New behavior: https://hydropandas--202.org.readthedocs.build/en/202/examples/02_knmi_observations.html

Old behavior: https://hydropandas.readthedocs.io/en/latest/examples/02_knmi_observations.html

**Comment by martinvonk** [comment]
Should be fixed now with https://github.com/ArtesiaWater/hydropandas/commit/1cedf7fbce6c1f8fade4d490fc6554285142a7d1.
