### ISSUE TITLE
Indexing ObsCollection always returns "obs" column

### ISSUE THREAD

**Issue by martinvonk** [ArtesiaWater/hydropandas#210]
Not sure why this happens but when I use `loc` on the ObsCollection the column with the "obs" is always returned

```python
oc_sel = oc.loc[:, ["x", "y"]]
oc_sel.columns -> Index(['x', 'y', 'obs'], dtype='object')
```
Same happens with iloc
`oc.iloc[:, [0,1]]`

**Comment by martinvonk** [comment]
This is the reason why #209 fails

**Comment by martinvonk** [comment]
Happened to me after updating pandas; 
Updating pandas (2.2.1 -> 2.2.2)

**Comment by martinvonk** [comment]
Not sure if we need to do something with this. #209 is already fixed. 
Maybe if behavior keeps existing after v2.2.2 we need to adress this.

**Comment by OnnoEbbens** [comment]
It has become an issue in the bro_bronhouder notebook now as well. I think it has something to do with this error: https://github.com/pandas-dev/pandas/issues/57032

**Comment by OnnoEbbens** [comment]
Geopandas had the same problem: https://github.com/geopandas/geopandas/issues/3060

**Comment by OnnoEbbens** [comment]
For now I will pin the pandas version to 2.2.1 or lower because this also gives errors in nlmod.
