### ISSUE TITLE
Bij het ophalen van meer dan 80 metingen krijg ik een 429 too many requests error

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/hydropandas#232]
Het lijkt erop alsof de BRO limieten heeft gezet op de hoeveelheid data/requests die je kan doen. Bij het ophalen van een dataset met 80 metingen krijg ik een 429 too many requests error. Ik ben benieuwd of anderen ditzelfde probleem hebben of dat het komt omdat ik al teveel data heb opgevraagd.

Om te reproduceren:
```
extent = [117602, 123712, 498014 , 502630]
oc = hpd.read_bro(extent, keep_all_obs=False)
```

**Comment by HMEUW** [comment]
Here it works fine.

![image](https://github.com/user-attachments/assets/ac7109e0-0dc6-4b4c-b876-c220c2ec6fca)

**Comment by OnnoEbbens** [comment]
Thanks Hendrik. I tried several times on different IP-adresses (I hope the BRO will not hate me for it). Sometimes I got the error sometimes not. For now I added some error handling that waits a second before trying again if a 429 is encountered.

**Comment by MattBrst** [comment]
As documentation for others: https://basisregistratieondergrond.nl/actueel/nieuws/nieuws/2024/december/opvraaglimieten-publieke-rest-services/

For the REST GLD endpoints they mention a maximum of 3 requests per second. The SOAP service is recommended if you want more.
