### ISSUE TITLE
Use start and end date for KNMI stations

### ISSUE THREAD

**Issue by rubencalje** [ArtesiaWater/hydropandas#238]
In PR #202 a lot of now inactive precipitation stations were added. These stations do not contain any data for recent years. However, when downloading data using 'fill_missing_measurements' hydropandas tries to download data for all these stations, which takes time and creates a lot of info-messages and warnings. On the site of the KNMI there are list of the start- and end-time of the precipitation and meterological stations:

https://www.knmi.nl/nederland-nu/klimatologie/monv/reeksen

https://www.knmi.nl/nederland-nu/klimatologie/daggegevens

I think we should use these start- and end-times (if not until last year), so we do not download stations with no recent data anymore.

**Comment by martinvonk** [comment]
```python
import pandas as pd
tables = pd.read_html('https://www.knmi.nl/nederland-nu/klimatologie/monv/reeksen', index_col=0)
pd.concat(tables)
```

**Comment by martinvonk** [comment]
There are a few neerslagstations where there is data but they are not in our knmi_neerslagstation.json. However the location is unknown (#131). For now, we'll ignore these locations until we find an xy location:

```
169	Amen	19680101 t/m 19741231
83	Balk	19500307 t/m 19560627
895	Blerick	19510102 t/m 19551231
138	Borger	19500221 t/m 19530430
916	Boxtel	19500402 t/m 19570607
322	Espel	19481001 t/m 19521231
585	Hilversum-Oost	19500102 t/m 19531231
62	Holwerd	19501129 t/m 19520331
355	Kamper Nieuwstad	19490501 t/m 19581231
351	Kavel B-86 (Rutten)	19481106 t/m 19531231
587	Kesteren	19500502 t/m 19551231
972	Maastricht	19461202 t/m 19561106
537	Nieuwland Zh	19421002 t/m 19511231
320	Nieuwleusen	19470801 t/m 19530228
63	Oosterend Fr	19510102 t/m 19551231
52	Oosternijkerk Fr	19600701 t/m 19600929
253	Oosthuizen Nh	19510102 t/m 19551231
167	Uithuizermeeden	19540301 t/m 19560528
220	Waarland Nh	19501118 t/m 19530331
545	Wageningen	19500215 t/m 19541130
88	Wierum	19520401 t/m 19600629
842	Willemstad	19460102 t/m 19551231
248	Wormer	19490401 t/m 19540630
```

**Comment by OnnoEbbens** [comment]
Nice! I think a nice implementation would be to add a `tmin` and `tmax` argument to the `io.knmi.get_stations` functions and have this function only return stations that have at least some data in the given period. I can implement this if you want?

**Comment by martinvonk** [comment]
Yes you can do it if you want. I didn't have the time today. Would speed things up considerably I think.

**Comment by dbrakenhoff** [comment]
There seems to be an issue when downloading data for a time series that does not contain measurements in the period requested.

To reproduce:
```python
hpd.read_knmi(stns=[739], starts="2023-12-01", ends="2024-03-28", meteo_vars=["RD"], fill_missing_obs=True)
```

When looking for the next nearest station, `get_nearest_station_df` fails because the station (739 in this example) is missing from the list since there are no observations. It feels a bit like some circular reasoning is going on, but the station for which the user is trying to download data should always be in the stations dataframe (otherwise you cannot determine what is nearest).

**Comment by OnnoEbbens** [comment]
Fixed  by Davíd himself
