### ISSUE TITLE
change repository name

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/hydropandas#26]
The name of this repository is too general. The repository cannot be used for any kind of observation (e.g. satellite observations) and is now only used for Dutch hydrological observations. Therefore I think we should change the name to something more specific. I thought of something like:
- hobsnl (**h**ydrological **obs**ervations **N**ether**l**ands)
- hydropandas (like geopandas but for hydrology)
- duhobs (**Du**tch **h**ydrological **obs**ervations)
- hobsio (**h**ydrological **obs**ervat**io**ns, **io** is ook een verwijzing naar de input/output features)

**Comment by dbrakenhoff** [comment]
I agree! I like a mostly pronouncable name that means something when you read it.  So I think I prefer something like hydropandas over duhobs/hobsio/hobsnl. But then again hydropandas is also quite general as a name... 

It seems quite challenging to find a name that specificies the focus on Dutch hydrological data (though the package isn't necessary limited to Dutch data of course) using pandas while keeping it readable. 

Just some random thoughts:
pyobsNL
hydrobspy
hydrogibbon
pyhydrodata

**Comment by OnnoEbbens** [comment]
I agree that a pronounceable name would be nice. I also like the idea of including pandas in the name because it is a big part of this package and has the same feel as geopandas. I was thinking how we could make the name specific and pronounceable but it's pretty hard. The best I could think of is hydrobspandas but I don't think it is very pronounceable.

Then I thought why not pretend as if the 'o' in hydropandas is for observations. Like **hydr**ological **o**bservations **pandas**

**Comment by dbrakenhoff** [comment]
Then I suggest we go for that one, if possible... Is Github case sensitive about repository names?

https://github.com/mullenkamp/HydroPandas

**Comment by OnnoEbbens** [comment]
I renamed the repository. I hope this doesn't break everything.

**Comment by OnnoEbbens** [comment]
It seems to work!
