### ISSUE TITLE
_check_latest_measurement_date_RD_debilt (io/io_knmi.py)

### ISSUE THREAD

**Issue by thomas-wsbd** [ArtesiaWater/hydropandas#54]
shouldn't line 237, be start instead of first None;
`knmi_df, variables = get_knmi_daily_rainfall(url, 550, "RD", start, None, False, verbose=verbose)`
furthermore current last measurement at De Bilt is at 2020-11-30, therefor checking for last 3 weeks of measurements seems to short.

best wishes ;)

**Comment by dbrakenhoff** [comment]
Way ahead of you! ;) 91f0d115fa0f4c4e1443aeaa36dfdc8ec7a00b4d

Just kidding, I just fixed this 2 days ago when we came across the same issue. But good spot, and thanks for letting us know!

**Comment by thomas-wsbd** [comment]
![](https://media.giphy.com/media/KzM1lAfJjCWNq/giphy.gif)

**Comment by OnnoEbbens** [comment]
The fix has been added to the latest PyPi release (0.3.3), closing the issue
