### ISSUE TITLE
Dino WSDL is down

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/hydropandas#56]
The WSDL service seems to have been taken down... :(

For reference this was the webservice URL: http://www.dinoservices.nl/gwservices/gws-v11?wsdl

Time to figure out how we can download the timeseries data now...

**Comment by OnnoEbbens** [comment]
Probably has to do with a migration to the BRO, still sad though.

**Comment by dbrakenhoff** [comment]
I found a possible suboptimal alternative via grondwatertools.nl. It's slow and I'm not entirely sure what data we'd be getting, but here it is anyway. Example:

```
https://www.grondwatertools.nl/metrandata/getloc?wellid=B32A1774&screenid=001
```

This returns a huge JSON document with all kinds of METRAN related info, but it also contains an entry `TS_FILTERED`, which nearest I can tell is the timeseries.

**Comment by dbrakenhoff** [comment]
Here is another query with the metadata for a well:

```
https://www.grondwatertools.nl/metrandata/selectwell?wellid=B32A1774
```

**Comment by OnnoEbbens** [comment]
The `DinoWSDL` class now raises an error when initiated. The test functions that use `DinoWSDL` are moved to a separate file and will be deleted in the next release.

For the future we can replace the functions with Davíd his grondwatertools method or wait for the BRO to come up with a decent API. For now I will close this issue.
