### ISSUE TITLE
building the docs failed

### ISSUE THREAD

**Issue by OnnoEbbens** [ArtesiaWater/hydropandas#68]
It seems like there is something wrong with the depencies at readthedocs, see this issue: https://github.com/readthedocs/readthedocs.org/issues/8639

**Comment by astrojuanlu** [comment]
Can you try adding `docutils<0.18` in `docs/requirements.txt` and see if it works?

By the way, you can enable Read the Docs on pull requests: https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by OnnoEbbens** [comment]
Thanks this worked!
