### ISSUE TITLE
only check last date De Bilt measurement if meteo_var = 'RD'

### ISSUE THREAD

**Issue by pimvansanten** [ArtesiaWater/hydropandas#70]
In the latest version, the function io_knmi.fill_missing_measurements() uses the condition meteo_var=='RH' to run function _check_latest_measurement_date_RD_debilt .
In previous versions (I only checked in 0.4.2) the condition was meteo_var == 'RD', which is correct in my opinion.
You only want to do this for the 'dagstations', not for the 'meteostations'.
Please have a look at this.

**Comment by dbrakenhoff** [comment]
We changed the variable to always be "RH" when downloading precipitation. I think to allow daily data at RH-stations (automatic weather stations) to be filled with data from RD (precipitation stations) stations. 

I'm not sure exactly how the checking is done now, given that change, but I will ask @OnnoEbbens to take a look when he's back from holiday.

Some discussion here: https://github.com/ArtesiaWater/hydropandas/pull/67
And a notebook showcasing the options here: https://github.com/ArtesiaWater/hydropandas/blob/master/examples/02_knmi_observations.ipynb

**Comment by OnnoEbbens** [comment]
According to https://github.com/ArtesiaWater/hydropandas/pull/67:

>  The fill_measurements function can now combine precipitation data from meteo- and neerslagstations. Only meteo stations record daily precipitation starting at 00:00 and neerslagstations record precipitation starting at 08:00 UTC. Combining them introduces errors.

I discussed with @dbrakenhoff and we think the best way forward is separating meteo and precipitation stations. You can fill missing values from nearby meteo stations if your initial station is a meteo stations and you can fill missing values at a precipitation station using nearby precipitation stations. If you wish to combine the data of meteo and precipitation station you can obtain both datasets and do this later yourself.
