### ISSUE TITLE
Read KNMI files locally

### ISSUE THREAD

**Issue by martinvonk** [ArtesiaWater/hydropandas#90]
I would like a feature where we can read KNMI observations (to an Obs(Collection)) from a local file. I know we already do this internally so it should not be that hard to implement right?

**Comment by OnnoEbbens** [comment]
Yeah good idea! The functions `get_knmi_daily_rainfall_url` and `get_knmi_daily_meteo_url` need to be modified slightly to allow this.

**Comment by OnnoEbbens** [comment]
Another wish: merge the `from_knmi`, `from_nearest_xy`, `from_obs` and `from_knmi_file` to one single method. Move all the logic to the io_knmi module

**Comment by martinvonk** [comment]
> Another wish: merge the `from_knmi`, `from_nearest_xy`, `from_obs` and `from_knmi_file` to one single method. Move all the logic to the io_knmi module

We could also rename `from_knmi` to `from_station` and let `from_knmi` autodetect whether the first argument is a tuple with x and y (call `from_nearest_xy`), is an int (call `from_station`), is a str (call `from_kni_file`)  etc. Then we can also leave the other methods intact at this place?
